golden_dataset = [
    {
        "produto": "Hidra Plus Sérum",
        "preco": "R$ 89,90",
        "ingrediente": "Ácido hialurônico",
        "tipo_pele": "Seca",
        "necessidade": "Hidratação",
    },
    {
        "produto": "Matte Control Gel",
        "preco": "R$ 59,90",
        "ingrediente": "Niacinamida",
        "tipo_pele": "Oleosa",
        "necessidade": "Controle de oleosidade",
    },
    {
        "produto": "Equilibra Creme",
        "preco": "R$ 74,90",
        "ingrediente": "Ceramidas",
        "tipo_pele": "Mista",
        "necessidade": "Equilíbrio",
    },
    {
        "produto": "Sensitiv Calm Loção",
        "preco": "R$ 69,90",
        "ingrediente": "Centelha asiática",
        "tipo_pele": "Sensível",
        "necessidade": "Redução de vermelhidão",
    },
    {
        "produto": "Anti-Sinais Noturno",
        "preco": "R$ 129,90",
        "ingrediente": "Retinol",
        "tipo_pele": "Madura",
        "necessidade": "Anti-idade",
    },
    {
        "produto": "Pure Clean Gel de Limpeza",
        "preco": "R$ 39,90",
        "ingrediente": "Ácido salicílico",
        "tipo_pele": "Oleosa",
        "necessidade": "Limpeza profunda",
    },
    {
        "produto": "Barreira Forte Loção",
        "preco": "R$ 84,90",
        "ingrediente": "Ceramidas",
        "tipo_pele": "Seca",
        "necessidade": "Redução de vermelhidão",
    },
    {
        "produto": "Toque de Seda Hidratante",
        "preco": "R$ 64,90",
        "ingrediente": "Glicerina",
        "tipo_pele": "Mista",
        "necessidade": "Hidratação",
    },
    {
        "produto": "Renove Clareador Facial",
        "preco": "R$ 99,90",
        "ingrediente": "Vitamina C",
        "tipo_pele": "Madura",
        "necessidade": "Clareamento de manchas",
    },
    {
        "produto": "Sun Shield FPS 60",
        "preco": "R$ 54,90",
        "ingrediente": "Óxido de zinco",
        "tipo_pele": "Sensível",
        "necessidade": "Proteção solar",
    },
    {
        "produto": "Oil Free Balance Tônico",
        "preco": "R$ 44,90",
        "ingrediente": "Ácido glicólico",
        "tipo_pele": "Oleosa",
        "necessidade": "Equilíbrio",
    },
    {
        "produto": "Nutri Repair Noturno",
        "preco": "R$ 94,90",
        "ingrediente": "Peptídeos",
        "tipo_pele": "Seca",
        "necessidade": "Anti-idade",
    },
]